// default package
// Generated 12-ago-2015 12:32:05 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellidos;
	private String dni;
	private Set userTeachers = new HashSet(0);

	public User() {
	}

	public User(String nombre, String apellidos, String dni) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
	}

	public User(String nombre, String apellidos, String dni, Set userTeachers) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.userTeachers = userTeachers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Set getUserTeachers() {
		return this.userTeachers;
	}

	public void setUserTeachers(Set userTeachers) {
		this.userTeachers = userTeachers;
	}

}
