// default package
// Generated 12-ago-2015 12:32:05 by Hibernate Tools 3.4.0.CR1

/**
 * UserTeacher generated by hbm2java
 */
public class UserTeacher implements java.io.Serializable {

	private Integer id;
	private User user;
	private String centro;
	private String asignatura;

	public UserTeacher() {
	}

	public UserTeacher(String centro, String asignatura) {
		this.centro = centro;
		this.asignatura = asignatura;
	}

	public UserTeacher(User user, String centro, String asignatura) {
		this.user = user;
		this.centro = centro;
		this.asignatura = asignatura;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCentro() {
		return this.centro;
	}

	public void setCentro(String centro) {
		this.centro = centro;
	}

	public String getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(String asignatura) {
		this.asignatura = asignatura;
	}

}
