package es.neodoo.model.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class TeacherVO implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellidos;
	private String dni;
	private Set userTeachersVO = new HashSet(0);

	public TeacherVO() {
	}

	public TeacherVO(String nombre, String apellidos, String dni) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
	}

	public TeacherVO(String nombre, String apellidos, String dni, Set userTeachersVO) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.userTeachersVO = userTeachersVO;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Set getUserTeachersVO() {
		return this.userTeachersVO;
	}

	public void setUserTeachersVO(Set userTeachersVO) {
		this.userTeachersVO = userTeachersVO;
	}

}
