package es.neodoo.model.vo;

// default package
// Generated 14-ago-2015 12:06:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserTeacher generated by hbm2java
 */
@Entity
@Table(name = "user_teacher", catalog = "curso")
public class UserTeacher implements java.io.Serializable {

	private Integer id;
	private User user;
	private String centro;
	private String asignatura;

	public UserTeacher() {
	}

	public UserTeacher(String centro, String asignatura) {
		this.centro = centro;
		this.asignatura = asignatura;
	}

	public UserTeacher(User user, String centro, String asignatura) {
		this.user = user;
		this.centro = centro;
		this.asignatura = asignatura;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "centro", nullable = false, length = 45)
	public String getCentro() {
		return this.centro;
	}

	public void setCentro(String centro) {
		this.centro = centro;
	}

	@Column(name = "asignatura", nullable = false, length = 45)
	public String getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(String asignatura) {
		this.asignatura = asignatura;
	}

}
