package es.neodoo.model.vo;

// default package
// Generated 14-ago-2015 12:06:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "curso")
public class User implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellidos;
	private String dni;
	private Set<UserTeacher> userTeachers = new HashSet<UserTeacher>(0);

	public User() {
	}

	public User(String nombre, String apellidos, String dni) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
	}

	public User(String nombre, String apellidos, String dni, Set<UserTeacher> userTeachers) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.userTeachers = userTeachers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", nullable = false, length = 45)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "dni", nullable = false, length = 45)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserTeacher> getUserTeachers() {
		return this.userTeachers;
	}

	public void setUserTeachers(Set<UserTeacher> userTeachers) {
		this.userTeachers = userTeachers;
	}

}
